### ISSUE TITLE
Usage with Unity

### ISSUE THREAD

**Issue by jjaine** [entrepreneur-interet-general/H3.Standard#2]
I've installed the package to Unity with NuGet, but I've got some problems. I can call the functions from the Unity code, but when I do that, I get a `DllNotFoundException` about the `h3lib.dll`. I'm calling the `InstanciateNativeLibrary` function, but that seems to put the `h3lib.dll` to the root of the project and Unity doesn't find it from there... If I add the `h3lib.dll` manually to `Assets/Plugins` in Unity, it can't find it, probably because it's not referenced in the `.csproj`. When trying to add the reference with Visual Studio, I get an error saying that the `h3lib.dll` is not a valid .NET assembly. Any suggestions on how I could get this working with Unity?

**Comment by ArnaudSwail** [comment]
This H3 binding is more than a year old.
I would first recommend to update to the latest version of the H3 native
library since this was bound in nov 2018.

Calling a C native lib from a managed dll within Unity seems to imply some
special care.
https://forum.unity.com/threads/il2cpp-missing-native-dll-referenced-by-managed-library.527808/

Hope this would help.

Le ven. 31 janv. 2020 à 16:10, Essi Jukkala <notifications@github.com> a
écrit :

**Comment by jjaine** [comment]
Hi, thanks for the tips! Ended up solving my problem by doing the C->C# wrapper and compiling the necessary .dll and .bundle myself to get this working with the least pain 😄

**Comment by Archi97** [comment]
@ijaine Hello. Could you please share the compiled dll file, or give me a small clue where to start.
Thanks

**Comment by ArnaudSwail** [comment]
Hello @Archi97,

best would be to get the C h3 library code locally and build it.
You can then add it to this c# solution and build the latter.
Support is now on C lib version 3.7.2.1

**Comment by Archi97** [comment]
> You can then add it to this c# solution and build the latter. Support is now on C lib version 3.7.2.1

Will also work on Android and IOS? and on different architectures?  or it depends on the build that i should do

**Comment by ArnaudSwail** [comment]
The c lib will have to be built for each target platform, definitely
